# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameProgramming', '0002_level_nextlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameProgramming.Level')),
            ],
        ),
    ]
