# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameProgramming', '0003_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='instruction',
            field=models.TextField(max_length=500),
        ),
    ]
